import { useState } from "react";
import "./App.css";

function App() {
  const [prompt, setPrompt] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function generateImage() {
    if (!prompt.trim()) {
      setError("プロンプトを入力してください。");
      return;
    }

    setLoading(true);
    setError("");
    setImageUrl("");

    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "画像生成に失敗しました。");
      }

      setImageUrl(data.imageUrl);
    } catch (err: any) {
      setError(err.message || "エラーが発生しました。");
    } finally {
      setLoading(false);
    }
  }

  async function downloadImage() {
    if (!imageUrl) return;

    const response = await fetch(imageUrl);
    const blob = await response.blob();
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = "moricanvas-ai-image.png";
    a.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="page">
      <section className="card">
        <div className="badge">🌿 MoriCanvas AI</div>

        <h1>風、光、森の気配まで描く AI作図サイト</h1>

        <p className="subtitle">
          入力した言葉から、やさしい手描きアニメ調の画像を生成します。
        </p>

        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="例：夕暮れの田舎道を歩く柴犬と小さな旅人。やさしい手描きアニメ調、温かい光、柔らかい色彩。"
        />

        <button onClick={generateImage} disabled={loading}>
          {loading ? "生成中..." : "画像を生成"}
        </button>

        {error && <p className="error">{error}</p>}

        {imageUrl && (
          <div className="result">
            <img src={imageUrl} alt="Generated by MoriCanvas AI" />
            <button onClick={downloadImage}>画像を保存</button>
          </div>
        )}

        <p className="footer">© 2026 MoriCanvas AI</p>
      </section>
    </main>
  );
}

export default App;
